# Generated by Django 5.2.13 on 2026-04-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_lesson', 'In Lesson'), ('resting', 'Resting'), ('retired', 'Retired')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='horses/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vet', 'Vet Visit'), ('farrier', 'Farrier Visit'), ('vaccination', 'Vaccination'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='horses.horse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
